menu:
  首页: /
  归档: /archives
  About: /resume

avatar: http://ww2.sinaimg.cn/large/7a0338aegw1ej12rnn2lyj2028028t8j.jpg

contact:
  googleplus:

excerpt_link: 阅读全文 >

duoshuo:
  shortname: Jruif

addthis:
  enable: false
  pubid:
  facebook: false
  twitter: false
  google: false
  pinterest: false

fancybox: true

analytics: true
## 谷歌统计需要id
google_analytics: false   
baidu_analytics: true
rss:
